#include "Service.h"
#include "Tests.h"
#include <assert.h>
#include <string.h>

void tests(void)
{
	Service serv;
	Repository* repo = createRepository(1);
	History* history = createHistory();
	serv.repo = repo;
	serv.history = history;
	addToRepo(serv, "med", "1", "1", "1");
	assert(serv.repo->capacity == 2);
	print_medicine(repo->meds[repo->capacity - 2]);
	printf("\nChecking Add Operation...\n");
	printf("Medicine has been added!\n");
	assert(history->capacity_undo == 2);
	printf("Repo added to undo!\n");
	printf("\nChecking Update Operation...\n");
	updateToRepo(serv, "med", "1", "red", "2", "3", "400");
	assert(strcmp(repo->meds[repo->capacity - 2].name, "red") == 0);
	printf("Name successfuly changed! | %s\n", repo->meds[repo->capacity - 2].name);
	assert(history->capacity_undo == 3);
	printf("Repo added to undo!\n");
	printf("\nChecking Delete Operation...\n");
	deleteInRepo(serv, "red", "2");
	assert(repo->capacity == 1);
	printf("Medicine has been deleted!\n");
	assert(history->capacity_undo == 4);
	printf("Repo added to undo!\n");
	printf("\nChecking Undo Operation...\n");
	Undo(serv);
	assert(repo->capacity == 2);
	printf("Repo has reverted back to the previous version!\n");
	assert(history->capacity_undo == 3);
	printf("Undo has been popped!\n");
	assert(history->capacity_redo == 2);
	printf("Pushed to Redo!\n");
	printf("\nChecking Redo Operation...\n");
	Redo(serv);
	assert(repo->capacity == 1);
	printf("Repo is back to being empty!\n");
	assert(history->capacity_redo == 1);
	printf("Redo has been popped!\n");
	assert(history->capacity_undo == 4);
	printf("Pushed to Undo!\n");
	printf("\n\nChecking Filters...\n");
	printf("Undo...\n");
	Undo(serv);
	print_medicine(repo->meds[repo->capacity - 2]);
	printf("\n");
	printf("Filtering by String: empty string\n");
	Repository* temp_repo_1 = DisplaySortedByGivenString(serv, "");
	assert(temp_repo_1->capacity == repo->capacity);
	printf("Same number of elements found!\n");
	destroyRepository(temp_repo_1);
	printf("Filtering by String: r\n");
	Repository* temp_repo_2 = DisplaySortedByGivenString(serv, "r");
	assert(temp_repo_2->capacity == repo->capacity);
	printf("Same number of elements found!\n");
	destroyRepository(temp_repo_2);
	printf("Filtering by String: l\n");
	Repository* temp_repo_3 = DisplaySortedByGivenString(serv, "l");
	assert(temp_repo_3->capacity != repo->capacity);
	printf("Different number of elements!\n");
	destroyRepository(temp_repo_3);
	printf("\n");
	printf("Filtering by Quantity: less than quantity\n");
	Repository* temp_repo_4 = LessThanQuantity(serv, 1);
	assert(temp_repo_4->capacity != repo->capacity);
	printf("Different number of elements!\n");
	destroyRepository(temp_repo_4);
	printf("Filtering by Quantity: equal to quantity\n");
	Repository* temp_repo_5 = LessThanQuantity(serv, repo->meds[repo->capacity - 2].quantity);
	assert(temp_repo_5->capacity != repo->capacity);
	printf("Different number of elements!\n");
	destroyRepository(temp_repo_5);
	printf("Filtering by Quantity: more than quantity\n");
	Repository* temp_repo_6 = LessThanQuantity(serv, repo->meds[repo->capacity - 2].quantity + 1);
	assert(temp_repo_6->capacity == repo->capacity);
	printf("Same number of elements found!\n");
	destroyRepository(temp_repo_6);
	printf("\n\nChecking operations failure...\n");
	printf("Redo...\n");
	Redo(serv);
	printf("\nCurrent repo size: %d / empty\n", repo->capacity);
	printf("Trying to delete / update the medicine with the name: red | concentration: 2\n");
	deleteInRepo(serv, "red", "2");
	updateToRepo(serv, "red", "2", "med", "1", "1", "1", "1");
	printf("\n\nChecking operation add for increasing quantity...\n");
	printf("Undo...\n");
	Undo(serv);
	print_medicine(repo->meds[repo->capacity - 2]);
	printf("\n");
	addToRepo(serv, "red", "2", "3", "100");
	assert(repo->capacity == 2);
	printf("Same number of element!\n");
	assert(repo->meds[repo->capacity - 2].quantity == 500);
	printf("Quantity changed to: %d\n", repo->meds[repo->capacity - 2].quantity);
}