%token CREATECOURSE ADDCOURSE SORTCOURSE PRINTCOURSE IF END ELIF ELSE FOR IN
%token COMMA DOUBLEEQUAL DIFFERENTOPERATOR LESSOPERATOR LESSOREQUALOPERATOR
%token GREATEROPERATOR GREATEROREQUALOPERATOR EXCLAMATION UPPERCOMMA DOT DOTANDCOMMA
%token SLASH DASH OPENROUNDEDPARANTHESIS CLOSEROUNDEDPARANTHESIS UNDERLINE EQUAL
%token OPENSQUAREDPARANTHESIS CLOSESQUAREDPARANTHESIS AND OR ASC DESC LENGTH SUM
%token FINALGRADE POSSIBLEGRADE OUTPUT DEF IDENTIFIER STRING BOOLEAN GRADE EPSILON